# Kritters
- type: department
  id: Cargo
  name: department-Cargo
  description: department-Cargo-description
  color: "#A46106"
  weight: -90
  primary: false
  editorHidden: true # Frontier

- type: department
  id: CentralCommand
  name: department-CentralCommand
  description: department-NFCentralCommand-description # Frontier
  color: "#0c344d"
  roles:
  - CentralCommandOfficial
#  - CBURN # Frontier
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
#  - DeathSquad # Frontier
  - ERTMailCarrier # Frontier
  editorHidden: true
  weight: 120

- type: department
  id: Command
  name: department-Command
  description: department-NFCommand-description # Frontier
  color: "#334E6D"
  # - Captain # Frontier
  # - ChiefEngineer # Frontier
  # - ChiefMedicalOfficer # Frontier
  # - HeadOfPersonnel # Frontier
  # - HeadOfSecurity # Frontier
  # - ResearchDirector # Frontier
  # - Quartermaster # Frontier
  # - CentralCommandOfficial # Frontier
  # - CBURN # Frontier
  # - ERTLeader # Frontier
  # - ERTChaplain # Frontier
  # - ERTJanitor # Frontier
  # - ERTMedical # Frontier
  # - ERTSecurity # Frontier
  # - ERTEngineer # Frontier
  # - DeathSquad # Frontier
  primary: false
  weight: 100
  editorHidden: true # Frontier

- type: department
  id: Silicon
  name: department-Silicon
  description: department-Silicon-description
  color: "#D381C9"
  roles:
  - StationAi
  editorHidden: true # Frontier
  primary: false # Frontier

- type: department
  id: Specific
  name: department-Specific
  description: department-Specific-description
  color: "#9FED58"
  weight: -91
  primary: false
  editorHidden: true # Frontier
