ConnectionStrings:
  DefaultConnection: "Server=127.0.0.1;Port=5432;Database=ss14;User Id=ss14_admin;Password=change-me"

AllowedHosts: "localhost"
urls: "http://0.0.0.0:8080/"
WebRootPath: "/app/wwwroot"

ForwardProxies:
  - 127.0.0.1

Auth:
  Authority: "https://account.spacestation14.com/"
  ClientId: "change-me"
  ClientSecret: "change-me"

authServer: "https://auth.spacestation14.com"
