services:
  ss14_admin:
    image: ghcr.io/space-wizards/ss14.admin:1
    container_name: ss14_admin
    user: 1654:1654
    volumes:
      - ./appsettings.yml:/app/appsettings.yml:ro,Z
    ports:
      - "127.0.0.1:27689:8080"
    restart: unless-stopped
